# Generated by Django 3.2.4 on 2021-06-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Depart_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_num', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('record', models.CharField(max_length=1000)),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.depart')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.user')),
            ],
        ),
    ]
