# Generated by Django 3.2.4 on 2021-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record',
            field=models.TextField(),
        ),
    ]
