# Generated by Django 3.2.4 on 2021-07-03 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_time',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 4, 3, 39, 25, 97990)),
        ),
    ]
