# Generated by Django 3.2.4 on 2021-07-03 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210704_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_time',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 4, 3, 40, 45, 1887)),
        ),
    ]
