# Generated by Django 3.2.5 on 2021-07-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('emp_num', models.IntegerField()),
                ('tel', models.IntegerField(blank=True)),
                ('id_num', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.department')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_num', models.CharField(max_length=50)),
                ('computer_name', models.CharField(max_length=50)),
                ('buy_time', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('computer_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.matuser')),
            ],
        ),
    ]
